Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-08, with the labels that each got.

#206 Expose configuration_workflow and workflow_job
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-configuration_workflow.rb
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-workflow_job.rb
  spec/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-configuration_workflow_spec.rb
Labels: enhancement

#205 Updating miq_task for the CustomButton request call with open_url.
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  spec/miq_ae_engine_spec.rb
Labels: blocker, bug, gaprindashvili/yes

#208 Handle MIQ_STOP in state machine processing
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_state_machine.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  spec/engine/miq_ae_state_machine_steps_spec.rb
Labels: bug

#214 Add plugin display name
  lib/manageiq/automation_engine/engine.rb
Labels: enhancement

#215 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-5
  CHANGELOG.md
Labels: documentation

#217 [Changelog] Update for Sprint 93
  CHANGELOG.md
Labels: documentation

#216 Add support to redhat VM for set_memory and set_number_of_cpus
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-redhat-infra_manager-vm.rb
  spec/service_models/miq_ae_service_manageiq-providers-redhat-infra_manager-vm_spec.rb
Labels: enhancement, gaprindashvili/yes
