Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-12, with the labels that each got.

#275 Add resource to conversion_host to pass validation
  spec/service_models/miq_ae_service_service_template_transformation_plan_task_spec.rb
Labels: bug

#276 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes

#277 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#265 Add automate method for external Ansible Job/Workflow template.
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_ansible_method_base.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_ansible_template_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_playbook_method.rb
  spec/miq_ae_ansible_template_method_spec.rb
Labels: enhancement

#282 [HAMMER] Bump hammer travis.yml to ruby 2.4.5
  .travis.yml
Labels: dependencies
