Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-11, with the labels that each got.

#264 [HAMMER] Add translations for hammer
  locale/es/ManageIQ_AutomationEngine.po
  locale/fr/ManageIQ_AutomationEngine.po
  locale/ja/ManageIQ_AutomationEngine.po
  locale/pt_BR/ManageIQ_AutomationEngine.po
  locale/zh_CN/ManageIQ_AutomationEngine.po
Labels: internationalization

#267 [GAPRINDASHVILI] Update the zone check during MiqQueue.put.
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
Labels: test

#266 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#270 [HAMMER] [Changelog] Update for Hammer RC-1
  CHANGELOG.md
Labels: documentation

#272 Make disconnect_storage a no-op
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb
  lib/miq_automation_engine/service_models/miq_ae_service_ems_event.rb
  spec/service_models/miq_ae_service_ems_event_spec.rb
Labels: blocker, bug, gaprindashvili/yes
