Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-09, with the labels that each got.

#219 Expose storage_profiles association in Storage's service model.
  lib/miq_automation_engine/service_models/miq_ae_service_storage.rb
Labels: bug, gaprindashvili/yes

#218 Add MiqWidget service model and expose queue_generate_content method
  lib/miq_automation_engine/service_models/miq_ae_service_miq_widget.rb
  spec/service_models/miq_ae_service_miq_widget_spec.rb
Labels: enhancement

#221 Bump rubyzip minimum version to 1.2.2
  manageiq-automation_engine.gemspec
Labels: dependencies

#222 Clear stale data from ae_state_data and ae_state_previous
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  spec/engine/miq_ae_state_machine_retry_spec.rb
Labels: blocker, bug, gaprindashvili/conflict, gaprindashvili/yes

#225 [WIP]delete_state_var method for MiqAeService.
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  spec/miq_ae_service_spec.rb
Labels: enhancement

#207 Allow for embedded methods to contain embedded methods
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
  spec/engine/miq_ae_method_spec.rb
Labels: enhancement

#227 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#212 Enable cancelation_status to be updated for service model
  lib/miq_automation_engine/service_models/miq_ae_service_service_template_transformation_plan_task.rb
Labels: bug

#224 [GAPRINDASHVILI] Clear stale data from ae_state_data and ae_state_previous
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  spec/engine/miq_ae_state_machine_retry_spec.rb
Labels: bug

#229 Exposes cancelation status to client side
  lib/miq_automation_engine/service_models/miq_ae_service_miq_request.rb
  lib/miq_automation_engine/service_models/miq_ae_service_miq_request_task.rb
Labels: enhancement, transformation

#226 MiqAeService spec correction
  spec/miq_ae_service_spec.rb
Labels: test

#232 Remove Gemnasium badge from README.md since it was discontinued
  README.md
Labels: documentation

#233 Correct gitter url to automate room
  README.md
Labels: documentation

#228 Clean up the password field and value in automate and evm.log
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_domain_search.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
Labels: blocker, bug, gaprindashvili/yes

#235 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#236 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
