Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-03, with the labels that each got.

#161 Fix removed have_attributes failures
  spec/models/miq_ae_domain_spec.rb
  spec/service_models/miq_ae_service_service_spec.rb
  spec/service_models/miq_ae_service_vm_spec.rb
Labels: test

#159 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation

#160 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#165 [Changelog] Add Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#157 Adds miq_ae_service_retire request and task
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb
  lib/miq_automation_engine/service_models/miq_ae_service_service_retire_request.rb
  lib/miq_automation_engine/service_models/miq_ae_service_service_retire_task.rb
  lib/miq_automation_engine/service_models/miq_ae_service_vm_retire_request.rb
  lib/miq_automation_engine/service_models/miq_ae_service_vm_retire_task.rb
Labels: enhancement

#166 use 2.3.6 on travis
  .travis.yml
Labels: test

#167 [GAPRINDASHVILI] use 2.3.6 on travis
  .travis.yml
Labels: test

#168 Don't call on_exit method while Ansible Playbook method is running.
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_playbook_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_state_machine.rb
  spec/engine/miq_ae_state_machine_steps_spec.rb
  spec/miq_ae_playbook_method_spec.rb
Labels: bug, gaprindashvili/yes
