Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-06, with the labels that each got.

#185 [Changelog] Update for Sprint 86
  CHANGELOG.md
Labels: documentation

#175 Service model: method exposing
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_base.rb
  spec/engine/miq_ae_method_service/miq_ae_service_model_base_spec.rb
Labels: bug, gaprindashvili/yes

#187 Adding the `storages` attribute to be exposed.
  lib/miq_automation_engine/service_models/miq_ae_service_vm_or_template.rb
Labels: bug, gaprindashvili/yes

#186 Expose task.mark_vm_migrated to Service.
  lib/miq_automation_engine/service_models/miq_ae_service_service_template_transformation_plan_task.rb
Labels: enhancement, gaprindashvili/yes, transformation

#189 [Changelog] Update for Sprint 88
  CHANGELOG.md
Labels: documentation

#183 Keep track of the server ids where the automate task has been processed.
  lib/miq_automation_engine/engine/miq_ae_engine.rb
Labels: enhancement

#190 Adds tracking label back to AeMethod lines
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
Labels: bug

#191 Add vm.remove_disk method for a VMware VM
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-vmware-infra_manager-vm.rb
Labels: enhancement

#193 Fix for ae_method copy with embedded methods.
  app/models/miq_ae_method_copy.rb
  spec/models/miq_ae_method_copy_spec.rb
Labels: bug

#194 Change code due to refactoring in Vmdb::Plugins
  app/models/miq_ae_datastore.rb
  app/models/miq_ae_domain.rb
Labels: refactoring
