Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-04, with the labels that each got.

#170 Expose generic_objects from GenericObjectDefinition.
  lib/miq_automation_engine/service_models/miq_ae_service_generic_object_definition.rb
Labels: bug, gaprindashvili/yes

#171 [Changelog] Update for Sprint 83
  CHANGELOG.md
Labels: documentation

#162 Change URI.split to replace double slashes with a single slash.
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_uri.rb
  spec/miq_ae_uri_spec.rb
Labels: bug, gaprindashvili/yes

#173 Expose initializing to automate
  lib/miq_automation_engine/service_models/mixins/miq_ae_service_retirement_mixin.rb
Labels: enhancement

#174 Add .yamllint from provider generator
  .yamllint
Labels: test

#176 [Changelog] Update for Sprint 84
  CHANGELOG.md
Labels: documentation
