Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-05, with the labels that each got.

#169 miq_ae_engine: deliver method refactoring.
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  spec/miq_ae_engine_spec.rb
Labels: refactoring

#177 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#178 Ability to add and remove volumes for an instance
  lib/miq_automation_engine/service_models/miq_ae_service_cloud_volume.rb
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-cloud_manager-vm.rb
Labels: enhancement

#112 Add support for accessing objects from anywhere in the workspace
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object_lookup.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  spec/miq_ae_assertion_spec.rb
  spec/miq_ae_engine_spec.rb
  spec/miq_ae_object_lookup_spec.rb
Labels: bug

#184 Directly append entires to the hash
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object_lookup.rb
Labels: cleanup

#182 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: test
