Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-10, with the labels that each got.

#237 Add some helper methods for MiqAeObject.
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_object_common.rb
  spec/engine/miq_ae_method_service/miq_ae_service_object_common_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#241 Remove check for nil zone during MiqQueue.put of GenericMailer
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
Labels: blocker, gaprindashvili/yes, hammer/yes, test

#242 Add orch stack retire task to vendor detect
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb
Labels: bug

#243 Use constant MASK for encrypted fields
  app/models/miq_ae_password.rb
Labels: technical debt

#245 Remove unneeded calls to stub_server_configuration
  spec/service_models/miq_ae_service_tenant_quota_spec.rb
  spec/service_models/miq_ae_service_tenant_spec.rb
Labels: technical debt, test

#240 [HAMMER] Update i18n catalog for hammer
  locale/ManageIQ_AutomationEngine.pot
  locale/en/ManageIQ_AutomationEngine.po
  locale/es/ManageIQ_AutomationEngine.po
  locale/fr/ManageIQ_AutomationEngine.po
  locale/ja/ManageIQ_AutomationEngine.po
  locale/pt_BR/ManageIQ_AutomationEngine.po
  locale/zanata.xml
  locale/zh_CN/ManageIQ_AutomationEngine.po
Labels: internationalization

#247 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#246 Expose ConversionHost and ServiceTemplateTransformationPlanTask methods
  lib/miq_automation_engine/service_models/miq_ae_service_conversion_host.rb
  lib/miq_automation_engine/service_models/miq_ae_service_service_template_transformation_plan_task.rb
Labels: enhancement, hammer/yes, transformation

#252 Fix class name for conversion host
  lib/miq_automation_engine/service_models/miq_ae_service_conversion_host.rb
Labels: bug, hammer/yes, transformation

#249 Take out detect vendor changes for orch stack retire tasks
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb
Labels: blocker, bug, hammer/yes

#254 [HAMMER] [Changelog] Add updates for beta1.1
  CHANGELOG.md
Labels: documentation

#257 Adjust Travis postgresql from 9.4 to 9.5
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes, test

#256 Expose folders to ems_folder service model.
  lib/miq_automation_engine/service_models/miq_ae_service_ems_folder.rb
Labels: enhancement, fine/yes, gaprindashvili/yes, hammer/yes

#255 Expose ext_management_system from ConversionHost
  lib/miq_automation_engine/service_models/miq_ae_service_conversion_host.rb
Labels: enhancement, hammer/yes, transformation

#253 Add conversion_host= method to MiqAeServiceServiceTemplateTransformationPlanTask
  lib/miq_automation_engine/service_models/miq_ae_service_service_template_transformation_plan_task.rb
  spec/service_models/miq_ae_service_service_template_transformation_plan_task_spec.rb
Labels: enhancement, hammer/yes, transformation

#244 Refactor extra_vars support for automate playbook method.
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_playbook_method.rb
Labels: enhancement

#258 convert_value_based_on_datatype won't take "Integer"
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  spec/miq_ae_object_spec.rb
Labels: bug, hammer/yes

#251 Use Open3.popen3 instead of Open4
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
Labels: hammer/no, technical debt

#262 [HAMMER] [Changelog] Update for Hammer Beta2
  CHANGELOG.md
Labels: documentation
