Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2018-07, with the labels that each got.

#188 Remove references to host provisioning
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  lib/miq_automation_engine/service_models/miq_ae_service_miq_host_provision.rb
  lib/miq_automation_engine/service_models/miq_ae_service_miq_host_provision_request.rb
  spec/miq_ae_engine_spec.rb
  spec/service_models/miq_ae_service_miq_host_provision_request_spec.rb
  spec/service_models/miq_ae_service_miq_host_provision_spec.rb
Labels: gaprindashvili/no, technical debt

#195 [Changelog] Update for Sprint 89
  CHANGELOG.md
Labels: documentation

#196 Added mock support for current
  spec/miq_ae_mock_service_spec.rb
  spec/support/miq_ae_mock_service.rb
Labels: technical debt, test

#197 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-4
  CHANGELOG.md
Labels: documentation

#199 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation

#200 Incorporating the deliver method change into the refactoring
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  spec/miq_ae_engine_spec.rb
Labels: bug

#201 Start the drb server with a unix socket
  lib/miq_automation_engine/engine/miq_ae_engine/drb_remote_invoker.rb
Labels: bug, fine/yes, gaprindashvili/yes

#203 Removed unknown service type test
  spec/service_models/miq_ae_service_service_template_spec.rb
Labels: technical debt, test

#204 [Changelog] Update for Sprint 91
  CHANGELOG.md
Labels: documentation
