Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-07, with the labels that each got.

#335 Add a rubocop channel to the codeclimate config
  .codeclimate.yml
Labels: bug, dependencies, test

#333 Save playbook set_stats data for successive playbook methods.
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_ansible_method_base.rb
  spec/miq_ae_playbook_method_spec.rb
Labels: enhancement

#318 Add scope to list automate domains from ancestors tenants
  app/models/miq_ae_domain.rb
  spec/miq_ae_domain_spec.rb
Labels: changelog/yes, enhancement

#328 Support for opening URL from the UI through automate.
  lib/miq_automation_engine/service_models/miq_ae_service_cloud_tenant.rb
  lib/miq_automation_engine/service_models/miq_ae_service_ext_management_system.rb
  lib/miq_automation_engine/service_models/miq_ae_service_generic_object.rb
  lib/miq_automation_engine/service_models/miq_ae_service_miq_group.rb
  lib/miq_automation_engine/service_models/miq_ae_service_service.rb
  lib/miq_automation_engine/service_models/miq_ae_service_user.rb
  lib/miq_automation_engine/service_models/miq_ae_service_vm.rb
  lib/miq_automation_engine/service_models/mixins/miq_ae_external_url_mixin.rb
Labels: changelog/yes, enhancement

#336 Add helper method ansible_stats_vars
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_ansible_method_base.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  spec/miq_ae_service_spec.rb
Labels: changelog/yes, enhancement

#338 Add service_vars to pass variables between catalog items in a bundle
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  lib/miq_automation_engine/service_models/miq_ae_service_service.rb
  spec/miq_ae_service_spec.rb
Labels: enhancement, hammer/no

#340 [Changelog] Update for Sprint 116
  CHANGELOG.md
Labels: documentation

#343 [Changelog] Update for Ivanchuk Beta1 release
  CHANGELOG.md
Labels: documentation, ivanchuk/yes
