Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-02, with the labels that each got.

#292 Redirect writable_storages to writable_accessible_storages
  lib/miq_automation_engine/service_models/miq_ae_service_host.rb
Labels: bug, hammer/no

#293 Don't set User.current_user
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  spec/engine/miq_ae_workspace_runtime_spec.rb
Labels: bug

#294 Update specs to conform to ConversionHost validations
  spec/service_models/miq_ae_service_service_template_transformation_plan_task_spec.rb
Labels: test, transformation

#297 [Changelog] Update for Sprint 105
  CHANGELOG.md
Labels: documentation

#295 Change Fixnum to Integer
  spec/models/miq_ae_class_copy_spec.rb
  spec/models/miq_ae_instance_copy_spec.rb
Labels: test

#299 Fix two deprecations
  spec/miq_ae_engine_spec.rb
  spec/models/miq_ae_method_copy_spec.rb
Labels: test

#300 [Changelog] Update for Hammer-3
  CHANGELOG.md
Labels: documentation, hammer/yes
