Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-08, with the labels that each got.

#321 Fix call to make_retire_request.
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
Labels: bug, changelog/yes, ivanchuk/yes

#347 [Changelog] Update for Hammer-10
  CHANGELOG.md
Labels: documentation, hammer/yes

#346 Clean up README formatting
  README.md
Labels: cleanup, documentation

#344 Expose move_into_folder on the engine
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-vmware-infra_manager-vm.rb
  spec/service_models/miq_ae_service_manageiq-providers-vmware-infra_manager-vm_spec.rb
Labels: changelog/yes, enhancement, ivanchuk/yes

#348 Override equality comparison method for MiqAeServiceModelBase
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_base.rb
Labels: changelog/yes, ivanchuk/yes, refactoring

#350 Add external_url= capability to Tenant.
  lib/miq_automation_engine/service_models/miq_ae_service_tenant.rb
Labels: bug, ivanchuk/yes

#345 Add method $evm.get_state_vars
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  spec/miq_ae_service_spec.rb
Labels: changelog/yes, enhancement, ivanchuk/no

#349 Undefine Kernel#display which would be called over service#display for DRbObject
  lib/miq_automation_engine/engine/miq_ae_engine/drb_remote_invoker.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes

#334 Fix the issue with null coalescing fields as input parameters.
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  spec/miq_ae_method_spec.rb
Labels: bug, changelog/yes, hammer/no, ivanchuk/yes

#351 [Changelog] Update for Sprint 118
  CHANGELOG.md
Labels: documentation

#354 Add MiqAeEngine.return_result.
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  spec/miq_ae_engine_spec.rb
Labels: bug, ivanchuk/yes
