Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-10, with the labels that each got.

#375 Bump version to 1.3.0 for CVE-2019-16892
  manageiq-automation_engine.gemspec
Labels: dependencies

#376 [Changelog] Update for Sprint 121
  CHANGELOG.md
Labels: documentation

#370 Correct style using rubocop (part 4)
  .rubocop_local.yml
  app/models/miq_ae_datastore.rb
  app/models/miq_ae_datastore/xml_import.rb
  app/models/miq_ae_datastore/xml_yaml_converter.rb
  app/models/miq_ae_yaml_export_zipfs.rb
  app/models/miq_ae_yaml_import_gitfs.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_expression_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_path.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_playbook_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_reference.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_state_machine.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_uri.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_base.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_rbac.rb
  spec/data/provision/SPEC_DOMAIN/EVMApplications/Provisioning/WHERE.class/__methods__/least_utilized.rb
  spec/miq_ae_object_spec.rb
  spec/models/miq_ae_method_compare_spec.rb
  spec/service_models/miq_ae_service_service_spec.rb
  spec/support/miq_automate_helper.rb
Labels: changelog/yes, ivanchuk/no, refactoring

#379 Remove #retire_service_resources
  lib/miq_automation_engine/service_models/miq_ae_service_service.rb
  spec/service_models/miq_ae_service_service_spec.rb
Labels: changelog/yes, cleanup, ivanchuk/no

#382 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
  spec/miq_ae_engine_spec.rb
Labels: changelog/yes, dependencies, test

#378 Cleanup after Ansible runner.
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_ansible_method_base.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_playbook_method.rb
  spec/miq_ae_playbook_method_spec.rb
Labels: changelog/yes, hammer/no, ivanchuk/yes, refactoring

#384 Sprints 122 and 123 Changelog
  CHANGELOG.md
Labels: documentation

#383 Cleanup after Ansible runner.
  lib/miq_automation_engine/service_models/miq_ae_service_service_template_ansible_playbook.rb
Labels: changelog/yes, hammer/no, ivanchuk/yes, refactoring
