Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-09, with the labels that each got.

#356 [Changelog] Update for Sprint 119
  CHANGELOG.md
Labels: documentation

#359 [WIP] [Changelog] Update for Ivanchuk-1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes, wip

#358 Add method to delete tag
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
Labels: changelog/yes, enhancement, ivanchuk/no

#363 Add method to delete category
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
Labels: changelog/yes, enhancement, ivanchuk/no

#364 Correct style using rubocop (part 1)
  app/models/miq_ae_browser.rb
  app/models/miq_ae_class_yaml.rb
  app/models/miq_ae_datastore.rb
  app/models/miq_ae_datastore/xml_import.rb
  app/models/miq_ae_domain.rb
  app/models/miq_ae_git_import.rb
  app/models/miq_ae_instance_copy.rb
  app/models/miq_ae_instance_yaml.rb
  app/models/miq_ae_method_yaml.rb
  app/models/miq_ae_yaml_export.rb
  lib/miq_automation_engine/engine/miq_ae_engine/drb_remote_invoker.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  spec/support/miq_ae_mock_object.rb
  spec/support/miq_ae_mock_service.rb
Labels: ivanchuk/no, refactoring

#367 update_attributes has been deprecated
  app/models/miq_ae_datastore.rb
  app/models/miq_ae_domain.rb
  app/models/miq_ae_git_import.rb
  app/models/miq_ae_yaml_import.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  lib/miq_automation_engine/service_models/miq_ae_service_miq_request.rb
  lib/miq_automation_engine/service_models/miq_ae_service_vm_or_template.rb
  lib/miq_automation_engine/service_models/mixins/miq_ae_service_miq_request_mixin.rb
  lib/miq_automation_engine/service_models/mixins/miq_ae_service_retirement_mixin.rb
  spec/engine/miq_ae_builtin_method_spec.rb
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
  spec/miq_ae_domain_spec.rb
  spec/miq_ae_object_spec.rb
  spec/miq_method_override_spec.rb
  spec/models/miq_ae_datastore_spec.rb
  spec/models/miq_ae_domain_spec.rb
  spec/models/miq_ae_yaml_import_export_spec.rb
  spec/service_models/miq_ae_service_ems_event_spec.rb
  spec/service_models/miq_ae_service_host_spec.rb
  spec/service_models/miq_ae_service_manageiq-providers-cloud_manager-provision_spec.rb
  spec/service_models/miq_ae_service_manageiq-providers-vmware-infra_manager-provision_spec.rb
  spec/service_models/miq_ae_service_miq_provision_request_spec.rb
  spec/service_models/miq_ae_service_miq_provision_spec.rb
  spec/service_models/miq_ae_service_miq_request_spec.rb
  spec/service_models/miq_ae_service_miq_request_task_spec.rb
  spec/service_models/miq_ae_service_orchestration_stack_spec.rb
  spec/service_models/miq_ae_service_service_reconfigure_task_spec.rb
  spec/service_models/miq_ae_service_service_spec.rb
  spec/service_models/miq_ae_service_service_template_provision_request_spec.rb
  spec/service_models/miq_ae_service_service_template_provision_task_spec.rb
  spec/service_models/miq_ae_service_service_template_spec.rb
  spec/service_models/miq_ae_service_spec.rb
  spec/service_models/miq_ae_service_vm_spec.rb
Labels: changelog/yes, ivanchuk/no, technical debt

#369 Correct style using rubocop (part 3)
  Rakefile
  app/models/miq_ae_browser.rb
  app/models/miq_ae_datastore.rb
  app/models/miq_ae_method_compare.rb
  app/models/miq_ae_yaml_import.rb
  bin/rails
  bin/setup
  lib/manageiq/automation_engine/syntax_checker.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_path.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_state_machine.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb
  lib/miq_automation_engine/service_models/miq_ae_service_service.rb
  lib/miq_automation_engine/service_models/miq_ae_service_service_template.rb
  lib/miq_automation_engine/service_models/miq_ae_service_vm_or_template.rb
  lib/miq_automation_engine/service_models/mixins/miq_ae_service_retirement_mixin.rb
  manageiq-automation_engine.gemspec
  spec/miq_ae_engine_spec.rb
  spec/miq_ae_object_spec.rb
  spec/miq_ae_provision_spec.rb
Labels: changelog/yes, ivanchuk/no, refactoring

#361 Replace `before(:each)` with `before`
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
  spec/miq_ae_collect_spec.rb
  spec/miq_ae_discovery_spec.rb
  spec/miq_ae_engine_spec.rb
  spec/miq_ae_method_spec.rb
  spec/miq_ae_object_spec.rb
  spec/miq_ae_provision_spec.rb
  spec/miq_ae_service_model_spec.rb
  spec/miq_ae_state_machine_spec.rb
  spec/models/miq_ae_browser_spec.rb
  spec/models/miq_ae_class_compare_fields_spec.rb
  spec/models/miq_ae_datastore/legacy_xml_import_spec.rb
  spec/models/miq_ae_datastore_spec.rb
  spec/models/miq_ae_domain_spec.rb
  spec/models/miq_ae_xml_yaml_converter_spec.rb
  spec/service_models/miq_ae_service_availability_zone_spec.rb
  spec/service_models/miq_ae_service_ems_event_spec.rb
  spec/service_models/miq_ae_service_flavor_spec.rb
  spec/service_models/miq_ae_service_host_aggregate_spec.rb
  spec/service_models/miq_ae_service_host_spec.rb
  spec/service_models/miq_ae_service_manageiq-providers-amazon-cloud_manager_spec.rb
  spec/service_models/miq_ae_service_manageiq-providers-cloud_manager-vm_spec.rb
  spec/service_models/miq_ae_service_manageiq-providers-google-cloud_manager_spec.rb
  spec/service_models/miq_ae_service_manageiq-providers-openstack-cloud_manager_spec.rb
  spec/service_models/miq_ae_service_manageiq-providers-vmware-infra_manager-provision_spec.rb
  spec/service_models/miq_ae_service_miq_provision_request_spec.rb
  spec/service_models/miq_ae_service_miq_provision_spec.rb
  spec/service_models/miq_ae_service_miq_request_spec.rb
  spec/service_models/miq_ae_service_miq_request_task_spec.rb
  spec/service_models/miq_ae_service_service_reconfigure_request_spec.rb
  spec/service_models/miq_ae_service_service_reconfigure_task_spec.rb
  spec/service_models/miq_ae_service_service_spec.rb
  spec/service_models/miq_ae_service_service_template_provision_request_spec.rb
  spec/service_models/miq_ae_service_service_template_provision_task_spec.rb
  spec/service_models/miq_ae_service_service_template_spec.rb
  spec/service_models/miq_ae_service_spec.rb
  spec/service_models/miq_ae_service_vm_spec.rb
Labels: duplicate, ivanchuk/no, refactoring

#371 Mask the password value in logs.
  lib/miq_automation_engine/engine/miq_ae_engine.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes

#372 [Changelog] Update for Sprint 120
  CHANGELOG.md
Labels: documentation

#355 Prevent git import to overwrite base system domain in datastore.
  app/models/miq_ae_yaml_import.rb
Labels: bug, changelog/yes, ivanchuk/no

#373 Switch find_by_* to lookup_by_*
  app/models/miq_ae_class_copy.rb
  app/models/miq_ae_datastore.rb
  app/models/miq_ae_datastore/xml_export.rb
  app/models/miq_ae_datastore/xml_import.rb
  app/models/miq_ae_datastore/xml_yaml_converter.rb
  app/models/miq_ae_instance_copy.rb
  app/models/miq_ae_method_copy.rb
  app/models/miq_ae_yaml_export.rb
  app/models/miq_ae_yaml_import.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_domain_search.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_base.rb
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
  spec/engine/miq_ae_method_spec.rb
  spec/engine/miq_ae_state_machine_multi_spec.rb
  spec/engine/miq_ae_state_machine_steps_spec.rb
  spec/miq_ae_collect_spec.rb
  spec/miq_ae_domain_spec.rb
  spec/miq_ae_method_spec.rb
  spec/miq_ae_object_spec.rb
  spec/miq_ae_provision_spec.rb
  spec/miq_ae_state_machine_spec.rb
  spec/miq_method_override_spec.rb
  spec/models/miq_ae_class_compare_fields_spec.rb
  spec/models/miq_ae_class_copy_spec.rb
  spec/models/miq_ae_domain_spec.rb
  spec/models/miq_ae_instance_compare_values_spec.rb
  spec/models/miq_ae_instance_copy_spec.rb
  spec/models/miq_ae_method_compare_spec.rb
  spec/models/miq_ae_method_copy_spec.rb
  spec/models/miq_ae_yaml_import_export_spec.rb
Labels: changelog/yes, ivanchuk/no, refactoring
