Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-11, with the labels that each got.

#386 Model InfraManager_EmsCluster was renamed to InfraManager_Cluster
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_legacy.rb
Labels: changelog/yes, ivanchuk/no, refactoring

#388 [IVANCHUK] Test ruby 2.5.5, see: https://github.com/ManageIQ/manageiq/pull/19468
  .travis.yml
Labels: test

#389 Optionally symlink spec/manageiq during bin/setup
  bin/setup
Labels: changelog/yes, enhancement, test

#391 Fix typo
  spec/miq_ae_engine_spec.rb
Labels: changelog/no, cleanup, developer, ivanchuk/no

#390 [HAMMER] Fix manageiq-content specs on hammer
  lib/miq_automation_engine/service_models/miq_ae_service_service_template_ansible_playbook.rb
Labels: bug, hammer/yes, test

#381 Update object based on ansible set_stats data.
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_ansible_method_base.rb
  spec/miq_ae_playbook_method_spec.rb
Labels: changelog/yes, enhancement, hammer/no, ivanchuk/no
