Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-01, with the labels that each got.

#280 [Changelog] Update for Sprint 101
  CHANGELOG.md
Labels: documentation

#286 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#287 Don't overwrite message in create_automation_object
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  spec/miq_ae_engine_spec.rb
Labels: bug, hammer/yes

#288 Use lazy evaluation
  spec/miq_ae_engine_spec.rb
Labels: cleanup, developer

#274 Refactoring automate system domain list to include legacy domains
  app/models/miq_ae_datastore.rb
  spec/models/miq_ae_datastore/data/automate_domain_list_tests/not_system/__domain__.yaml
  spec/models/miq_ae_datastore/data/automate_domain_list_tests/system/__domain__.yaml
  spec/models/miq_ae_datastore_spec.rb
Labels: bug

#285 Removing empty option hash from automate method export.
  app/models/miq_ae_yaml_export.rb
  spec/models/miq_ae_yaml_import_export_spec.rb
Labels: bug

#290 [Changelog] Update for Sprint 103
  CHANGELOG.md
Labels: documentation
