Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-03, with the labels that each got.

#301 Remove openshift deployment stuff
  lib/miq_automation_engine/service_models/miq_ae_service_authentication_rhsm.rb
  lib/miq_automation_engine/service_models/miq_ae_service_container_deployment.rb
  lib/miq_automation_engine/service_models/miq_ae_service_container_deployment_node.rb
Labels: hammer/no, technical debt

#304 MiqAeMethodCopy: fix for broken copy method
  app/models/miq_ae_method_copy.rb
  spec/models/miq_ae_method_copy_spec.rb
Labels: bug

#305 Remove references to MiqPassword
  app/models/miq_ae_password.rb
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_domain_search.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  spec/engine/miq_ae_method_service/miq_ae_service_object_common_spec.rb
  spec/miq_ae_object_spec.rb
  spec/models/miq_ae_password_spec.rb
Labels: technical debt

#307 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation
