Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-04, with the labels that each got.

#311 Remove tags from dynamic association creation
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_base.rb
  spec/engine/miq_ae_method_service/miq_ae_service_model_base_spec.rb
Labels: bug, hammer/no

#312 Update .travis.yml PostgreSQL version to 10
  .travis.yml
Labels: enhancement

#283 Add helper method #create_job for Ansible Tower Job/Workflow template.
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-configuration_script.rb
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-configuration_workflow.rb
  spec/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-configuration_script_spec.rb
  spec/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-configuration_workflow_spec.rb
Labels: bug, hammer/yes

#313 Add functionality for bcc/cc
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
Labels: enhancement

#316 Move GIT_REPO_DIRECTORY constant from MiqAeDatastore to GitRepository
  app/models/miq_ae_datastore.rb
Labels: refactoring

#314 Add create_retire_request in the miq_ae_service_methods.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
Labels: bug, hammer/yes

#284 Add AE method for external Ansible Job/Workflow template
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_ansible_template_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
  spec/miq_ae_ansible_template_method_spec.rb
Labels: enhancement

#306 Physical server provisioning via StateMachine
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_builtin_method.rb
  spec/engine/miq_ae_builtin_method_spec.rb
  spec/service_models/miq_ae_service_physical_server_spec.rb
Labels: enhancement
