Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-12, with the labels that each got.

#396 Test an EMS that doesn't use streaming refresh
  spec/service_models/miq_ae_service_ems_event_spec.rb
Labels: test

#393 Add service#set_automate_timeout to save timeout into options hash
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  lib/miq_automation_engine/service_models/miq_ae_service_service.rb
  spec/miq_ae_service_spec.rb
Labels: changelog/yes, enhancement

#397 Update rubyzip to 2.0.0
  app/models/miq_ae_yaml_export_zipfs.rb
  app/models/miq_ae_yaml_import_zipfs.rb
  manageiq-automation_engine.gemspec
  spec/models/miq_ae_yaml_import_export_spec.rb
Labels: dependencies, enhancement

#400 Add back missing requires for rubyzip
  app/models/miq_ae_yaml_export_zipfs.rb
  app/models/miq_ae_yaml_import_zipfs.rb
  spec/models/miq_ae_yaml_import_export_spec.rb
Labels: bug

#387 Reducing the amount of data being stored in yaml file for svc_models
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_base.rb
  spec/engine/miq_ae_method_service/miq_ae_service_model_base_spec.rb
Labels: enhancement

#401 Changelog for Sprint 126
  CHANGELOG.md
Labels: documentation

#399 Update service_vars with playbook set_stats data.
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_ansible_method_base.rb
  spec/miq_ae_playbook_method_spec.rb
Labels: changelog/yes, enhancement, hammer/no, ivanchuk/no

#404 Add cc and bcc into builtin method send_email's inputs fields.
  app/models/miq_ae_datastore.rb
Labels: bug, changelog/yes, hammer/yes, ivanchuk/yes

#402 [Changelog] Update for Sprints 124 and 125
  CHANGELOG.md
Labels: blocker, documentation

#403 Initial CODEOWNERS checkin
  .github/CODEOWNERS
Labels: changelog/no, documentation
