Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2019-05, with the labels that each got.

#309 [HAMMER] Expose switches on hammer infra_managers
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-infra_manager.rb
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-redhat-infra_manager.rb
Labels: enhancement

#315 Add tests for orch stack retirement
  spec/service_models/miq_ae_service_orchestration_stack_spec.rb
Labels: test

#323 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#303 Support Export/Import of Domain with Ansible Method
  app/models/miq_ae_yaml_export.rb
  app/models/miq_ae_yaml_import.rb
  spec/models/miq_ae_yaml_import_export_spec.rb
Labels: enhancement

#319 Expose Ansible Tower TemplateRunner to service model.
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-template_runner.rb
  spec/service_models/miq_ae_service_manageiq-providers-ansible_tower-automation_manager-template_runner_spec.rb
Labels: enhancement, hammer/no

#325 [Changelog] Update for Hammer-6
  CHANGELOG.md
Labels: documentation, hammer/yes
