Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2020-02, with the labels that each got.

#415 Guard against hitting const_missing from within const_missing
  lib/miq_automation_engine/engine/miq_ae_method_service.rb
Labels: bug, changelog/yes

#417 [Changelog] Update for Sprint 129
  CHANGELOG.md
Labels: changelog/no, documentation

#422 A storage now has a direct belongs_to on ems_id
  spec/miq_ae_event_spec.rb
Labels: bug

#420 Add a method to resize a VMware VM Disk
  lib/miq_automation_engine/service_models/miq_ae_service_manageiq-providers-vmware-infra_manager-vm.rb
  spec/service_models/miq_ae_service_manageiq-providers-vmware-infra_manager-vm_spec.rb
Labels: enhancement

#416 Fix set_vm_notes spec
  spec/service_models/miq_ae_service_miq_provision_spec.rb
Labels: technical debt

#423 Change options accessing syntax in spec
  spec/service_models/miq_ae_service_miq_provision_spec.rb
Labels: changelog/yes, ivanchuk/yes, refactoring

#424 Fix other places we're using @miq_provision[:options] rather than .options
  spec/service_models/miq_ae_service_manageiq-providers-vmware-infra_manager-provision_spec.rb
  spec/service_models/miq_ae_service_miq_provision_request_spec.rb
Labels: changelog/yes, ivanchuk/no, refactoring

#398 Warning message for imported service models related to non-existing ar_models
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_base.rb
  spec/engine/miq_ae_method_service/miq_ae_service_model_base_spec.rb
Labels: bug

#428 [Changelog] Update for Sprint 130
  CHANGELOG.md
Labels: changelog/no, documentation

#374 Rubocop correction 5
  Rakefile
  app/models/miq_ae_class_copy.rb
  app/models/miq_ae_datastore.rb
  app/models/miq_ae_datastore/xml_export.rb
  app/models/miq_ae_datastore/xml_import.rb
  app/models/miq_ae_domain.rb
  app/models/miq_ae_instance_copy.rb
  app/models/miq_ae_method_copy.rb
  app/models/miq_ae_yaml_import_consolidated.rb
  lib/miq_automation_engine/engine/miq_ae_engine.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_ansible_method_base.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_domain_search.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_object_lookup.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_path.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_state_machine.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  lib/miq_automation_engine/engine/miq_ae_event.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_methods.rb
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_base.rb
  lib/miq_automation_engine/service_models/miq_ae_service_generic_object.rb
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
  spec/miq_ae_path_spec.rb
  spec/miq_ae_serialize_workspace_spec.rb
  spec/miq_ae_service_model_spec.rb
  spec/miq_ae_state_machine_new_spec.rb
  spec/miq_ae_state_machine_spec.rb
  spec/models/miq_ae_class_copy_spec.rb
  spec/models/miq_ae_datastore_spec.rb
  spec/models/miq_ae_instance_copy_spec.rb
  spec/models/miq_ae_method_copy_spec.rb
  spec/models/miq_ae_yaml_import_export_spec.rb
  spec/models/miq_ae_yaml_import_gitfs_spec.rb
  spec/service_models/miq_ae_service_generic_object_spec.rb
  spec/service_models/miq_ae_service_miq_provision_request_spec.rb
  spec/service_models/miq_ae_service_miq_provision_spec.rb
  spec/service_models/miq_ae_service_miq_request_spec.rb
  spec/service_models/miq_ae_service_service_spec.rb
  spec/service_models/miq_ae_service_vm_spec.rb
Labels: changelog/yes, ivanchuk/no, refactoring
