Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2020-10, with the labels that each got.

#455 Plugin Generator Updates
  .codeclimate.yml
  .gitignore
  .rspec_ci
  .rubocop.yml
  .rubocop_cc.yml
  .travis.yml
  .yamllint
  Gemfile
  README.md
  Rakefile
  bin/ci/after_failure
  bin/ci/after_script
  bin/rails
  bin/update
  bundler.d/.keep
  config/settings.yml
  lib/manageiq-automation_engine.rb
  lib/manageiq/automation_engine/engine.rb
  lib/tasks/README.md
  lib/tasks_private/spec.rake
  locale/.keep
  manageiq-automation_engine.gemspec
  spec/spec_helper.rb
Labels: developer

#457 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: dependencies

#458 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-automation_engine.gemspec
Labels: developer, enhancement

#459 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#460 rename factorygirl to factorybot
  spec/miq_ae_ansible_template_method_spec.rb
Labels: test
