Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2020-01, with the labels that each got.

#407 Use YAML.load to load classes beyond the basic types
  spec/engine/miq_ae_method_service/miq_ae_service_model_base_spec.rb
  spec/engine/miq_ae_state_machine_retry_spec.rb
Labels: bug, changelog/no, hammer/yes, ivanchuk/yes

#405 State var yaml to binary blob
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_workspace_runtime.rb
  lib/miq_automation_engine/engine/miq_ae_engine/state_var_hash.rb
  spec/engine/miq_ae_method_service/miq_ae_service_methods_spec.rb
  spec/engine/miq_ae_state_machine_retry_spec.rb
  spec/lib/miq_automation_engine/engine/miq_ae_engine/state_var_hash_spec.rb
  spec/miq_ae_ansible_template_method_spec.rb
  spec/miq_ae_deserialize_workspace_spec.rb
  spec/miq_ae_engine_spec.rb
  spec/miq_ae_playbook_method_spec.rb
  spec/miq_ae_service_spec.rb
  spec/service_models/miq_ae_service_generic_object_spec.rb
  spec/support/miq_ae_mock_service.rb
Labels: changelog/yes, ivanchuk/no, refactoring, unmergeable

#408 Sprint 127 changelog updates.
  CHANGELOG.md
Labels: changelog/no, documentation

#412 Replace dynamic find and uri escape
  app/models/miq_ae_instance_copy.rb
  app/models/miq_ae_yaml_import.rb
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_uri.rb
  spec/models/miq_ae_instance_compare_values_spec.rb
  spec/models/miq_ae_instance_copy_spec.rb
Labels: changelog/yes, ivanchuk/no, refactoring

#413 [Changelog] Update for Sprint 128
  CHANGELOG.md
Labels: changelog/no, documentation

#406 State var limit key type
  lib/miq_automation_engine/engine/miq_ae_engine/state_var_hash.rb
  spec/lib/miq_automation_engine/engine/miq_ae_engine/state_var_hash_spec.rb
Labels: changelog/yes, ivanchuk/no, technical debt

#414 Modify CODEOWNERS file for changelog.md updates
  .github/CODEOWNERS
Labels: changelog/no, documentation, ivanchuk/no
