Repository ManageIQ/manageiq-automation_engine, pull requests merged in 2023-12, with the labels that each got.

#536 Const get
  lib/miq_automation_engine/engine/miq_ae_method_service/miq_ae_service_model_base.rb
Labels: bug, developer

#538 Allow StateVarHash to YAML.load from runtime instantiate
  spec/engine/miq_ae_state_machine_retry_spec.rb
Labels: test

#537 permit_concurrent_loads is not needed with zeitwerk autoloader
  lib/miq_automation_engine/engine/miq_ae_engine/miq_ae_method.rb
Labels: enhancement, technical debt, rails7
